### ISSUE TITLE
DRI JPEG marker is not treated as having a length byte

### ISSUE THREAD

**Issue by lrosenthol** [paolobarbolini/img-parts#1]
In marker.rs, there is a method (https://github.com/paolobarbolini/img-parts/blob/master/src/jpeg/markers.rs#L90) that determines whether a given marker has a length so the copier knows how many bytes to copy.  

Unfortunately, it does not include the `DRI` marker in this list - thus any JPEG containing a `DRI` marker will be copied incorrectly and thus yield a damaged JPEG.

Simply adding `DRI` to the match block will resolve the issue.

**Comment by paolobarbolini** [comment]
Thanks for the report! Fixed in 214f337. I'll probably release v0.2.3 in a couple of hours.

**Comment by lrosenthol** [comment]
That's wonderful - thanks for the fast service!

**Comment by paolobarbolini** [comment]
[img-parts v0.2.3](https://crates.io/crates/img-parts/0.2.3) is out. Closing
