### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by lnicola** [paolobarbolini/img-parts#3]
Can you please cut out a new release (for the `bytes` dependency, at least)? Thanks!

**Comment by scouten-adobe** [comment]
Another vote for a newer release, at least for bytes dependency.

**Comment by paolobarbolini** [comment]
Sorry for the huge delay in me making a new release. Released as v0.3.0

**Comment by lnicola** [comment]
Thank you, but I don't even remember what I was using your crate for 😅.
